name: Cluster Setup
description: Cluster setup for e2e tests
inputs:
  github-token:
    description: GITHUB_TOKEN from the calling workflow
    required: true

runs:
  using: "composite"
  steps:
    - name: setup golang
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: setup minikube
      uses: manusa/actions-setup-minikube@v2.6.0
      with:
        minikube version: "v1.24.0"
        kubernetes version: "v1.23.0"
        start args: --memory 6g --cpus=2 --addons ingress --cni=calico
        github token: ${{ inputs.github-token }}

    - name: install deps
      shell: bash --noprofile --norc -eo pipefail -x {0}
      run: |
          sudo wget https://github.com/mikefarah/yq/releases/download/3.4.1/yq_linux_amd64 -O /usr/local/bin/yq
          sudo chmod +x /usr/local/bin/yq

    - name: print k8s cluster status
      shell: bash --noprofile --norc -eo pipefail -x {0}
      run: |
          kubectl cluster-info
          kubectl get pods -n kube-system

    - name: build operator image
      shell: bash --noprofile --norc -eo pipefail -x {0}
      run: IMG=controller:alpha make docker-build
