# permissions for end users to view objectstores.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: objectstore-viewer-role
rules:
- apiGroups:
  - object.rook-s3-nano
  resources:
  - objectstores
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - object.rook-s3-nano
  resources:
  - objectstores/status
  verbs:
  - get
