apiVersion: object.rook-s3-nano/v1alpha1
kind: ObjectStore
metadata:
  name: objectstore-sample
spec:
  image: quay.ceph.io/ceph-ci/ceph:wip-librados-wrapper-8-af9b01c-centos-stream8-x86_64-devel
  volumeClaimTemplate:
    spec:
      storageClassName: standard
      resources:
        requests:
          storage: 1Gi
  multisite:
    realmTokenSecretName: edge-object-store-realm-token
